export const EMPLOYEE_SET_EMPLOYEES='EMPLOYEE_SET_EMPLOYEES';
export const EMPLOYEE_SET_EMPLOYEE='EMPLOYEE_SET_EMPLOYEE';
export const EMPLOYEE_DELETE_EMPLOYEE='EMPLOYEE_DELETE_EMPLOYEE';
export const LOADING_TOOGLE_LOADING ='LOADING_TOOGLE_LOADING';
